### ISSUE TITLE
Index error

### ISSUE THREAD

**Issue by BakingBrains** [clovaai/voxceleb_trainer#103]
Traceback (most recent call last):
  File "/home/acharyaece/PycharmProjects/Speaker_recog/voxceleb/vox2_aac2/dev/aac/trainSpeakerNet.py", line 285, in <module>
    main()
  File "/home/acharyaece/PycharmProjects/Speaker_recog/voxceleb/vox2_aac2/dev/aac/trainSpeakerNet.py", line 281, in main
    main_worker(0, None, args)
  File "/home/acharyaece/PycharmProjects/Speaker_recog/voxceleb/vox2_aac2/dev/aac/trainSpeakerNet.py", line 144, in main_worker
    train_dataset = train_dataset_loader(**vars(args))
  File "/home/acharyaece/PycharmProjects/Speaker_recog/voxceleb/vox2_aac2/dev/aac/DatasetLoader.py", line 124, in __init__
    dictkeys = list(set([x.split()[0] for x in lines]))
  File "/home/acharyaece/PycharmProjects/Speaker_recog/voxceleb/vox2_aac2/dev/aac/DatasetLoader.py", line 124, in <listcomp>
    dictkeys = list(set([x.split()[0] for x in lines]))
IndexError: list index out of range

any suggestion??

**Comment by BakingBrains** [comment]
resolved
