### ISSUE TITLE
The password and username

### ISSUE THREAD

**Issue by harlanhong** [clovaai/voxceleb_trainer#129]
How can I get the username and password?

**Comment by ngoanpv** [comment]
@harlanhong Find the form on https://www.robots.ox.ac.uk/~vgg/data/voxceleb/vox2.html

**Comment by Mercurise** [comment]
Hi @ngoanpv , could you highlight the form pls, I couldn't find any form in the provided link? Could you also confirm the download links are still valid in mid-2022? 

Thanks.
```

python ./dataprep.py --save_path ../dataset_dir/ --download --user USERNAME --password PASSWORD


--2022-05-06 09:49:14--  http://www.robots.ox.ac.uk/~vgg/data/voxceleb/vox1a/vox1_dev_wav_partaa
Resolving www.robots.ox.ac.uk (www.robots.ox.ac.uk)... 129.67.94.2
Connecting to www.robots.ox.ac.uk (www.robots.ox.ac.uk)|129.67.94.2|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://www.robots.ox.ac.uk/~vgg/data/voxceleb/vox1a/vox1_dev_wav_partaa [following]
--2022-05-06 09:49:14--  https://www.robots.ox.ac.uk/~vgg/data/voxceleb/vox1a/vox1_dev_wav_partaa
Connecting to www.robots.ox.ac.uk (www.robots.ox.ac.uk)|129.67.94.2|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2022-05-06 09:49:14 ERROR 404: Not Found.

Traceback (most recent call last):
  File "./dataprep.py", line 176, in <module>
    download(args,fileparts)
  File "./dataprep.py", line 58, in download
    raise ValueError('Download failed %s. If download fails repeatedly, use alternate URL on the VoxCeleb website.'%url)
ValueError: Download failed http://www.robots.ox.ac.uk/~vgg/data/voxceleb/vox1a/vox1_dev_wav_partaa. If download fails repeatedly, use alternate URL on the VoxCeleb website.
```

**Comment by raotnameh** [comment]
@Mercurise Have you been able to download the data?
