### ISSUE TITLE
How to test with a different test list?

### ISSUE THREAD

**Issue by dimuthuanuraj** [clovaai/voxceleb_trainer#133]
hi @dvisockas @joonson, if we want to test with a new test list from a different dataset,  Can we do it by changing only the test list?

**Comment by joonson** [comment]
Yes, test list and test path.

**Comment by dimuthuanuraj** [comment]
@joonson. I tried that but I am getting this error. 

Python Version: 3.8.10 (default, Jun  4 2021, 15:09:15) 
[GCC 7.5.0]
PyTorch Version: 1.9.0+cu102
Number of GPUs: 1
Save path: exps/test
Embedding size is 512, encoder SAP.
Initialised AngleProto
Initialised Adam optimizer
Initialised step LR scheduler
Model baseline_lite_ap.model loaded!
Total parameters:  1437078
Test list /mnt/ricproject4/anuraj_works/data_collection/YoutubeVideos/Results_Videos/finallist_s00.txt
Traceback (most recent call last):
  File "./trainSpeakerNet.py", line 316, in <module>
    main()
  File "./trainSpeakerNet.py", line 312, in main
    main_worker(0, None, args)
  File "./trainSpeakerNet.py", line 199, in main_worker
    sc, lab, _ = trainer.evaluateFromList(**vars(args))
  File "/mnt/ricproject4/commercial_product/speaker_verification/anuraj/voxceleb_trainer_4/voxceleb_trainer/SpeakerNet.py", line 178, in evaluateFromList
    for idx, data in enumerate(test_loader):
  File "/home/anuraj/anaconda3/envs/vox_trainer/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/home/anuraj/anaconda3/envs/vox_trainer/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1203, in _next_data
    return self._process_data(data)
  File "/home/anuraj/anaconda3/envs/vox_trainer/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1229, in _process_data
    data.reraise()
  File "/home/anuraj/anaconda3/envs/vox_trainer/lib/python3.8/site-packages/torch/_utils.py", line 425, in reraise
    raise self.exc_type(msg)
TypeError: __init__() missing 1 required positional argument: 'dtype'``

**Comment by dimuthuanuraj** [comment]
@joonson  Problem solved. My data set had stereo wave files. To process the data we need to only mono wave files. Thank you.
