### ISSUE TITLE
KeyError: 'id10004/JKMfqmjUwMU/00003.wav'

### ISSUE THREAD

**Issue by VenkatesanSoundirarajan** [clovaai/voxceleb_trainer#143]
Hi,
Thanks for this great work.
I'm getting following error while executing trainSpeakerNet.py with customized(less number of samples from voxceleb1) dataset for training and evaluation. But I got this error and I couldn't solve this issue.

Please help me to resolve this issue.

Reading 0 of 37: 0.00 Hz, embedding size 512
Computing 0 of 143: 0.00 HzTraceback (most recent call last):
File "./trainSpeakerNet.py", line 310, in
main()
File "./trainSpeakerNet.py", line 304, in main
mp.spawn(main_worker, nprocs=n_gpus, args=(n_gpus, args))
File "/opt/conda/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 230, in spawn
return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
File "/opt/conda/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 188, in start_processes
while not context.join():
File "/opt/conda/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 150, in join
raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException:

-- Process 0 terminated with the following error:
Traceback (most recent call last):
File "/opt/conda/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 59, in _wrap
fn(i, *args)
File "/workspace/work/voxceleb_trainer-master/trainSpeakerNet.py", line 193, in main_worker
sc, lab, _ = trainer.evaluateFromList(**vars(args))
File "/workspace/work/voxceleb_trainer-master/SpeakerNet.py", line 221, in evaluateFromList
com_feat = feats[data[2]].cuda()
KeyError: 'id10004/JKMfqmjUwMU/00003.wav'

**Comment by msh9184** [comment]
Did you solve it? I think you should check your customized test_list file and the test_path you set.
