### ISSUE TITLE
Error in evaluateFromList() from SpeakerNet.py 

### ISSUE THREAD

**Issue by gems047** [clovaai/voxceleb_trainer#150]
Am training below and getting  error
python ./trainSpeakerNet.py --model VGGVox --log_input True --encoder_type SAP --trainfunc angleproto --save_path exps/exp2 --nClasses 5994 --batch_size 200

Looks like test audios in test_list are not getting accepted. provided similar path and format (.wav) for dev(train_list) and test(test_list)

Error:

File "/voxceleb_trainer/SpeakerNet.py", line 182, in evaluateFromList
     for idx, data in enumerate(test_loader):
  File "/miniconda3/envs/voxpy37/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 530, in __next__
    data = self._next_data()
  File "/miniconda3/envs/voxpy37/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1224, in _next_data
    return self._process_data(data)
  File "/miniconda3/envs/voxpy37/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1250, in _process_data
    data.reraise()
  File "/miniconda3/envs/voxpy37/lib/python3.7/site-packages/torch/_utils.py", line 457, in reraise
    raise exception
RuntimeError: Caught RuntimeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/miniconda3/envs/voxpy37/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/miniconda3/envs/voxpy37/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/miniconda3/envs/voxpy37/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/voxceleb_trainer/DatasetLoader.py", line 179, in __getitem__
    audio = loadWAV(os.path.join(self.test_path,self.test_list[index]), self.max_frames, evalmode=True, num_eval=self.num_eval)
  File "/voxceleb_trainer/DatasetLoader.py", line 32, in loadWAV
    audio, sample_rate = soundfile.read(filename)
  File "/miniconda3/envs/voxpy37/lib/python3.7/site-packages/soundfile.py", line 257, in read
    subtype, endian, format, closefd) as f:
  File "/miniconda3/envs/voxpy37/lib/python3.7/site-packages/soundfile.py", line 629, in __init__
    self._file = self._open(file, mode_int, closefd)
  File "/miniconda3/envs/voxpy37/lib/python3.7/site-packages/soundfile.py", line 1184, in _open
    "Error opening {0!r}: ".format(self.name))

File "/miniconda3/envs/voxpy37/lib/python3.7/site-packages/soundfile.py", line 1357, in _error_check
    raise RuntimeError(prefix + _ffi.string(err_str).decode('utf-8', 'replace'))
RuntimeError: Error opening '/voxceleb_trainer/data/voxceleb1/id00685': File contains data in an unknown format.

**Comment by Jungjee** [comment]
I checked and modified in #154. Please check out this version.
