### ISSUE TITLE
Issues with pretrained model `RawNet3/model.pt`

### ISSUE THREAD

**Issue by SangwonSUH** [clovaai/voxceleb_trainer#157]
Hi,
- I'm trying to reproduce the evaluation EER of the provided pretrained models with the instructions from the README file.
- It was successful with the model `ResNetSE34V2`, but `RawNet3` has some issues

## Issues

1. There was no config file named `configs/RawNet3.yaml`
   - Is it okay to use the `RawNet3_AAM.yaml` instead?
3. Errors from `loadParameters`
    ```python
    Traceback (most recent call last):
      File "./voxceleb_trainer/./trainSpeakerNet.py", line 276, in <module>
        main()
      File "./voxceleb_trainer/./trainSpeakerNet.py", line 272, in main
        main_worker(0, None, args)
      File "./voxceleb_trainer/./trainSpeakerNet.py", line 165, in main_worker
        trainer.loadParameters(args.initial_model)
      File "./voxceleb_trainer/SpeakerNet.py", line 248, in loadParameters
        loaded_state = torch.load(path, map_location="cuda:%d" % self.gpu)
      File "/home/miniconda3/envs/torch/lib/python3.9/site-packages/torch/serialization.py", line 608, in load
        return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
      File "/home/miniconda3/envs/torch/lib/python3.9/site-packages/torch/serialization.py", line 777, in _legacy_load
        magic_number = pickle_module.load(f, **pickle_load_args)
    _pickle.UnpicklingError: invalid load key, 'v'.
    ```

## Tests
I've tried the `trainSpeakerNet.py` script with followings
  - Python env.
    ```bash
    python                    3.9.9           h543edf9_0_cpython    conda-forge
    pytorch                   1.10.1          py3.9_cuda11.3_cudnn8.2.0_0    pytorch
    torchaudio                0.10.1          py39_cu113    pytorch
    ```
  - Python cmd
    ```bash
    CUDA_VISIBLE_DEVICES=0 python ./trainSpeakerNet.py --eval --config ./configs/RawNet3_AAM.yaml --initial_model RawNet3/model.pt
    ```

---
Thanks for your efforts in maintaining this repository.

**Comment by SangwonSUH** [comment]
It was git-lfs issue
Pull `RawNet3/model.pt` with following cmd
```bash
# ./voceleb_trainer/RawNet3
git lfs pull
```
