### ISSUE TITLE
ValueError: source code string cannot contain null bytes

### ISSUE THREAD

**Issue by dendi123** [clovaai/voxceleb_trainer#56]
Hi, Since I'm kinda new to VGGVox and Python, I'm currently trying to train VGGVox Model but I have some errors when running the trainning code
`python ./trainSpeakerNet.py --model ResNetSE34L --log_input True --encoder SAP --trainfunc amsoftmax --save_path ./data/exp1 --nSpeakers 5994 --batch_size 200 --scale 30 --margin 0.3 --train_list ./train_list.txt --test_list ./test_list.txt --train_path ./voxceleb/voxceleb2 --test_path ./voxceleb/voxceleb1`

**Actual Behavior**
Traceback (most recent call last):
  File "./trainSpeakerNet.py", line 93, in <module>
    s = SpeakerNet(**vars(args));
  File "D:\VGGvox\VGGvoxtrainer\voxceleb_trainer\SpeakerNet.py", line 19, in __init__
    SpeakerNetModel = importlib.import_module('models.'+model).__getattribute__('MainModel')
  File "G:\Anaconda\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "D:\VGGvox\VGGvoxtrainer\voxceleb_trainer\models\VGGVox.py", line 5, in <module>
    import torchaudio
ValueError: source code string cannot contain null bytes

I got this errors with ResNetSE34L and VGGVox
a different error shown up with ResNetSE34 but I think I can handle that
**Your System configuration**
Python version: 3.5.6
torch 1.6.0
torchaudio 0.6.0

Thanks,
Wish you have a good day

**Comment by joonson** [comment]
Hi, Windows platform is not supported.

**Comment by huyvl** [comment]
> Hi, Windows platform is not supported.

Oh thanks you. Very appreciate that
